baseurl: 'https://shreyasjejurkar.com/'
title: Shreyas Jejurkar blog
languageCode: en-US
theme: "PaperMod"
permalinks:
  blog: '/:year/:month/:day/:slug'
params:
  env: production
  avatar: profile.png
  description: "Shreyas Jejurkar blog"
  keywords: [Blog, Portfolio, Shreyas Jejurkar, Microsoft, Software Engineer, Windows, Programming, Technology, Misc]
  custom_css: []
  custom_js: []
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: true
  comments: true
  homeInfoParams:
    Title: Hi there, I'm Shreyas Jejurkar, welcome to my digital space.
    Content: "Currently I am working as Software Engineer at Microsoft. 
    Here you will find blogs on various topics like Windows, programming, technology, misc etc."
  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/ShreyasJejurkar"
    - name: "github"
      url: "https://github.com/ShreyasJejurkar"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/shreyasjejurkar/"
    - name: "linktree"
      url: "https://linktr.ee/ShreyasJejurkar"
minify:
  disableXML: true
  minifyOutput: true
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
pygmentsUseClasses: true
enableRobotsTXT: true
googleAnalytics: G-VCJBTDWJZP
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
